
TASK_IDS  := eng-fin
TRAINDATA := multisynt_tower/parallel/tower72b


MIN_SRCSEQ_LENGTH := 2
MIN_TRGSEQ_LENGTH := 2


## use document-level tokenizers trained on Tatoeba/HPLT/MultiSynth
VOCAB := tatoeba_hplt_multisynt


## include this at the end to set all variables and
## to include all makefile targets for marmot experiments
include ../../make/marmot.mk

