

# from https://zenodo.org/records/3707949
# HF: https://huggingface.co/datasets/community-datasets/tapaco

tapaco_v1.0.zip:
	wget -O $@ https://zenodo.org/records/3707949/files/tapaco_v1.0.zip?download=1

