

TASKS     := eng-eng
TRAINDATA := instruct/train
DEVDATA   := instruct/dev
VOCAB     := tatoeba_hplt_multisynt

MODEL_ARCHITECTURE := transformer-xl
PRETRAINED_MODEL   := ../predict-eng-xl/mammoth
BATCH_SIZE         := 16384

include ../../../make/marmot.mk
