

TASKS     := eng-eng
TRAINDATA := multisynt/textpredict/train/len1024
DEVDATA   := multisynt/textpredict/dev/len1024
VOCAB     := tatoeba_hplt_multisynt

MODEL_ARCHITECTURE := transformer-xl
BATCH_SIZE         := 16384

include ../../../make/marmot.mk
