#-*-makefile-*-


## set experiment parameters (if different from defaults)

MODEL_NAME      := fin-eng
TASKS           := fin-eng
ENCODER_LAYERS  := 6
DECODER_LAYERS  := 6


## include common configuration and make targets
## and set environment (if different from standard)

include ../../../make/marmot.mk

