task_id: task_eng-ita

tasks:
  task_eng-ita:
    src_tgt: "eng-ita"
    weight: 1.0
    introduce_at_training_step: 0
    node_gpu: "1:5"
    enc_sharing_group: ["eng","gmw","all"]
    dec_sharing_group: ["all","roa","ita"]
    transforms: [filtertoolong]
    path_src: /scratch/project_462000964/MARMoT/data/tatoeba/train/eng-ita.eng.gz
    path_tgt: /scratch/project_462000964/MARMoT/data/tatoeba/train/eng-ita.ita.gz
    path_valid_src: /scratch/project_462000964/MARMoT/data/tatoeba/dev5K/eng-ita.eng.gz
    path_valid_tgt: /scratch/project_462000964/MARMoT/data/tatoeba/dev5K/eng-ita.ita.gz


src_vocab:
   eng: /scratch/project_462000964/MARMoT/tokenizer/tatoeba/eng/32000/tokenizer.json
tgt_vocab:
   ita: /scratch/project_462000964/MARMoT/tokenizer/tatoeba/ita/32000/tokenizer.json
# Model Architecture Options
enc_layers: [3,3,3]
dec_layers: [3,3,3]

model_dim: 768      
dropout: 0.1      
model_dtype: bf16     
add_language_tokens: false

# x-transformers specific options
x_transformers_opts:
  attn_flash: true     
  rotary_pos_emb: true     
  tie_embedding: false    
  heads: 12
  pre_norm: false
  post_emb_norm: true
  post_emb_norm_bias: true
  attn_dropout: 0.1
  ff_dropout: 0.1
  layernorm_bias: true
  use_abs_pos_emb: false


# Decoding parameters
beam_size: 4
batch_size: 32
batch_type: sents

# GPU settings
gpu: 0
world_size: 1
gpu_ranks: [0]

seed: 42
src:  /scratch/project_462000964/MARMoT/data/flores200/devtest/eng_Latn.devtest
output: /pfs/lustrep1/scratch/project_462000964/members/tiedeman/MARMoT/sandbox/tiedeman/eucore/eucore/eval/eng_Latn.ita
model: /pfs/lustrep1/scratch/project_462000964/members/tiedeman/MARMoT/sandbox/tiedeman/eucore/eucore/model
